Fix#8 the default value of keepgenerated is false only in JDK 6.
eclipse-ee4j/wasp pull request #26
Opened 2021-06-21 08:00 UTC by hs536

The default value for JSP keepgenerated should be false in JDK 6 or later, but only in JDK 6.

Signed-off-by: hs536 <sawamura.hiroki@fujitsu.com>

2021-06-21 12:42 UTC, joakime requested changes

2021-06-21 12:42 UTC, joakime commented on src/main/java/org/apache/jasper/EmbeddedServletOptions.java
> +        Double version = Double.valueOf(System.getProperty("java.specification.version"));
This will trigger a NumberFormatException on many JVMs.

2021-06-21 12:44 UTC, joakime commented
With the next version of Jakarta EE (Jakarta EE 10), there is a strong chance that it will have Java 11 as the minimum supported version of Java.
This JVM specific concept in EmbeddedServletOptions will probably just be removed at that point.

2021-06-22 00:27 UTC, hs536 commented on src/main/java/org/apache/jasper/EmbeddedServletOptions.java
> +        Double version = Double.valueOf(System.getProperty("java.specification.version"));
> This will trigger a NumberFormatException on many JVMs.

Isn't it when we refer to "java.version" or "java.runtime.version"? Do you know of any distributions that have a non-numeric value for "java.specification.version"?

2021-06-22 14:38 UTC, joakime commented on src/main/java/org/apache/jasper/EmbeddedServletOptions.java
> +        Double version = Double.valueOf(System.getProperty("java.specification.version"));
The `java.specification.version` property was not declared that it shall be VNUM only until JEP223 hit.

For full OpenJDK releases you can rely on `java.specification.version` being a VNUM in the vast majority of cases.
With the one exception being mistakes made by various early access releases (and experimental releases) from various vendors.

But, if we include a larger scope, like Java 1.6 JVM variants outside of OpenJDK (or even compact profile only releases within OpenJDK).
Then it's a virtual wild-west of smaller embedded system JVMs and adherence to what those properties mean.

We've hit this several times with Eclipse Jetty.
If this were to be merged, I would encourage a try/catch wrap for NumberFormatException (perhaps a `ServletContext.log()` of the error), and returning a sane default in those cases.

Ultimately though, I don't think this is a useful thing to even exist in EmbeddedServletOptions, as JSP/WASP current releases I believe are JDK 8+ anyway.

https://github.com/eclipse-ee4j/wasp/blob/3.0.1/pom.xml#L162-L163

https://github.com/eclipse-ee4j/wasp/blob/5d3a1535cc8b2ccbb8e00df48b69dce8fade0c18/pom.xml#L162-L163

This concept should probably just be removed, support for JVMs earlier than 1.6 isn't even a thing right now.

2021-06-24 08:52 UTC, hs536 commented on src/main/java/org/apache/jasper/EmbeddedServletOptions.java
> +        Double version = Double.valueOf(System.getProperty("java.specification.version"));
Thank you for your kind explanation!
As you pointed out, since JSP/WASP is unlikely to work with JDKs older than JDK6 in the future, so I've changed the commit to set keepgenerated to false regardless of JDK version.

2021-09-07 02:13 UTC, hs536 commented
@joakime @arjantijms 
This PR was finally fixed by removing the special handling with JDK 6. Is there anything else I can do?

2021-09-09 14:52 UTC, joakime approved these changes
@markt-asf you good with this change?

2021-09-09 15:29 UTC, markt-asf commented
I have no objection but my opinion shouldn't count much as I'm not involved in the Jakarta implementation work at Eclipse.
On a mostly unrelated topic, I did notice that WASP is still using the `org.apache.jasper` package. Changing the package name is long overdue in my view.

2021-09-09 16:01 UTC, joakime commented
> On a mostly unrelated topic, I did notice that WASP is still using the `org.apache.jasper` package. Changing the package name is long overdue in my view.

Yeah, that should be a new issue / pr IMO

2021-09-09 16:03 UTC, joakime commented
@markt-asf opened issue about package namespace as https://github.com/eclipse-ee4j/wasp/issues/29

2021-09-09 16:03 UTC, joakime commented
@arjantijms you have any objections with this PR?

2021-09-09 16:46 UTC, arjantijms commented
@joakime it looks fine, indeed no need to keep anything JDK 6 around.

A tiny remark, and that's here:

```java
private boolean keepGenerated = false;
```

`false` is already the default for a `boolean` field, so there's no need to set it explicitly.

2021-09-10 04:17 UTC, hs536 commented
> false is already the default for a boolean field, so there's no need to set it explicitly.

Yes, I understand the default values are defined clearly because they correspond to jasper options.

https://github.com/eclipse-ee4j/wasp/blob/91c16e50ba12c7255f9a90b9d68829cdf637d8c6/src/main/java/org/apache/jasper/EmbeddedServletOptions.java#L59-L72

2021-11-01 02:33 UTC, hs536 commented
@joakime Is there anything else I can do to merge this fix?

2021-11-27 00:29 UTC, arjantijms commented
It looks good, thanks! We may pretty soon indeed set the defaults to JDK 11.

2021-11-27 00:29 UTC, merged